title: My Docs Site
description: Example documentation website with GitHub Pages
theme: minima

url: "https://kanujgit.github.io"
baseurl: "/doc"

search_enabled: true
nav_order: 1

nav:
  - title: "Getting Started"
    url: /getting-started
  - title: "Installation"
    url: /installation
  - title: "Usage"
    url: /usage
  - title: "FAQ"
    url: /faq

